# Generated by Django 4.2.23 on 2025-07-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book',
            field=models.BooleanField(default=False),
        ),
    ]
